# Generated by Django 4.1.1 on 2022-09-18 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2021),
                        ]
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("SU", "Summer"),
                            ("FA", "Fall"),
                            ("WI", "Winter"),
                            ("SP", "Spring"),
                        ],
                        max_length=5,
                    ),
                ),
                ("comestible", models.BooleanField(default=True)),
                ("wikipedia", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("sold", models.BooleanField(default=False)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2021),
                        ]
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CL", "Clothing"),
                            ("GA", "Gaming"),
                            ("HO", "Home"),
                            ("M", "Miscellaneous"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
