# Generated by Django 4.1.1 on 2022-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="second_type",
            field=models.CharField(
                choices=[
                    ("CL", "Clothing"),
                    ("GA", "Gaming"),
                    ("HO", "Home"),
                    ("M", "Miscellaneous"),
                ],
                default="",
                max_length=6,
            ),
            preserve_default=False,
        ),
    ]
