# Generated by Django 4.1.1 on 2022-09-18 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_second_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="year",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2021),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="year",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2021),
                ],
            ),
        ),
    ]
