# Generated by Django 4.1.1 on 2022-09-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_band_year_alter_listing_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="second_type",
        ),
    ]
